### PR TITLE
fix: state and ui fixes

### LINKED ISSUE #1325: 0.8.35 mining does not stop, processes continue, and close hangs the app
**Describe the bug**
On Windows, start mining. Then Stop. Process does not stop, and closing the app hangs it.

### PR DESCRIPTION
**Pull request by Misieq01**
### [ Summary ]
- Fixed updating metrics state
- Fixed gpu availability detection
- Removed legacy hardware monitor implementation

### CODE REVIEW

**Review by stringhandler — APPROVED** [review]
Just some lint errors that need fixing

**Comment by stringhandler** [comment]
Tested it out but still freezes when closing

**Comment by Misieq01** [comment]
@stringhandler, yeah, wanted to improve mainly animations here, the issue with closing the app I wanted to tackle down in another PR as its currently in various cases, I'm not sure how long it would take to fix it so before that I wanted to prioritize fixing reward history issue

**Comment by stringhandler** [comment]
Sounds good

File: src/hooks/mining/useMiningStatesSync.ts [hunk 1]
```diff
@@ -37,6 +37,7 @@ export function useMiningStatesSync() {
         const ul = listen('miner_metrics', async ({ payload }) => {
             if (!payload) return;
             const payloadChanged = !deepEqual(payload as MinerMetrics, prevPayload.current);
+            console.log('Payload changed', payloadChanged);
```
Comment (stringhandler) [inline src/hooks/mining/useMiningStatesSync.ts:40]:
```suggestion
```

File: src/hooks/mining/useMiningMetricsUpdater.ts [hunk 2]
```diff
@@ -6,6 +6,7 @@ import { useMiningStore } from '@app/store/useMiningStore';
 import { useBlockchainVisualisationStore } from '@app/store/useBlockchainVisualisationStore.ts';
 
 import useFetchTx from './useTransactions.ts';
+import { useAppStateStore } from '@app/store/appStateStore.ts';
```
Comment (stringhandler) [inline src/hooks/mining/useMiningMetricsUpdater.ts:9]:
```suggestion
```
