### PR TITLE
fix: autoUpdate interval logic

### LINKED ISSUE #487: Change 5 minute check for autoupdate to show dialog instead of just installing it

### PR DESCRIPTION
**Pull request by shanimal08**
Description
---
- `useMainAppVersion` hook was no longer needed as a the update logic was added in `AutoUpdateDialog`, so removed that hook
- just added the 5 minute interval to `AutoUpdateDialog` to check for an update, and moved the `onUpdaterEvent` listener to its own useEffect

Motivation and Context
---

- resolves #487

### CODE REVIEW

File: src/containers/AutoUpdateDialog/AutoUpdateDialog.tsx [hunk 1]
```diff
@@ -20,36 +22,26 @@ function AutoUpdateDialog() {
...
-                    console.info('New Tari Universe version available', manifest);
-                    setLatestVersion(manifest?.version);
-                    setOpen(true);
-                } else {
-                    setIsAfterAutoUpdate(true);
-                }
-            } catch (error) {
-                console.error(error);
+    const checkUpdateTariUniverse = useCallback(async () => {
+        console.debug('hi');
```
Comment (mmrrnn) [inline src/containers/AutoUpdateDialog/AutoUpdateDialog.tsx:26]: hi

Comment (shanimal08) [reply src/containers/AutoUpdateDialog/AutoUpdateDialog.tsx:26]: ah heck 😅 thanks!

File: src/containers/AutoUpdateDialog/AutoUpdateDialog.tsx [hunk 2]
```diff
@@ -20,36 +22,26 @@ function AutoUpdateDialog() {
...
-        return () => {
-            unlistenPromise?.then((unlisten) => unlisten());
-        };
+        } catch (error) {
+            console.error(error);
+            setIsAfterAutoUpdate(true);
+        }
     }, [setIsAfterAutoUpdate]);
 
+    useInterval(() => checkUpdateTariUniverse(), UPDATE_CHECK_INTERVAL);
```
Comment (mmrrnn) [inline src/containers/AutoUpdateDialog/AutoUpdateDialog.tsx:43]: use `useEffect` to clear interval when unmounted

**Review by mmrrnn — APPROVED** [review]

**Review by mmrrnn — APPROVED** [review]

**Review by stringhandler — APPROVED** [review]
