### PR TITLE
fix(ui): animation updates | transaction & earnings fixes | miner metrics and stores cleanups

### LINKED ISSUE #1198: Windows: Won on my pc but now the UI is stuck here post catch up animation
**Describe the bug**
image
in this state, replay doesnt work
and there is no way to get it back to the original block animation
however when miimized it will report on additional winnings, just without the animation

### LINKED ISSUE #1318: 0.8.34 Red long block doesn't animate
**Describe the bug**
On both Windows and Mac, long block is broken. It it winks but never animates out.

https://www.loom.com/share/26a28ed11b094e2c8b2fb0326f6e53d2

### PR DESCRIPTION
**Pull request by shanimal08**
w## Description

**reverted back to actual tauri crate in this PR**

- updated animation build so you can show a replay if not started
- updated on our side to remove starting the animation if not mining (just pass isReplay)
- removed the extra `miner_metrics` listener in [`useSystemTray`](https://github.com/tari-project/universe/pull/1229/files#diff-0f8836d7c431878dea871d881c7beb5bdc2926ab237fe7dba0a0948338e6f77a), and just use the store values instead
- split out miner metrics from the mining store to its own store, [`useMiningMetricsStore`](https://github.com/tari-project/universe/pull/1229/files#diff-3fc3d5af17dd298493c576af53a4508d2495560802e3fcd66d5b447003d4e017)
  - cleaned up mining stores (visualizations, metrics, and ui)
  - moved some actions out of the mining stores to be used outside of hooks ([`miningStoreActions`](https://github.com/tari-project/universe/pull/1229/files#diff-8932d256e2c3fb7ca702d495c4548e785826b529ae16113f71f96534e24a0c78))
- [changed `get_tari_wallet_details` to an emit instead of calling the command from FE at an interval](https://github.com/tari-project/universe/pull/1229/files#diff-2f5e0a90d4195e9986f5e24928dce16b59a80a2cf30f7059b38d55bd7d1eff69R540-R555)
- bump oudated deps
- added splashscreen window to capabilities files
- standardise getting app window - using `getCurrentWindow` whereas before we had a mix of `getCurrentWindow` and `getCurrentWebviewWindow`
- use `app.emit` instead of window in `telemetry_manager`
- removed unnecessary intervals in favour of listeners
- added `useDeferredValue` in places we needed to check for 'stale' data

## Motivation and Context

Fixes #1198
Fixes #1318

## How Has This Been Tested?

https://github.com/user-attachments/assets/2a3faf5d-2d4b-43c2-b990-2ad86fd52574

https://github.com/user-attachments/assets/56310c51-959e-4df7-9955-62fa29eb1378

https://github.com/user-attachments/assets/ee8e5a90-7eb0-4377-b5e7-4318c5261a79

## What process can a PR reviewer use to test or verify this change?

- check that long block and earnings animations work as expected 
  - normal earnings
  - missed earnings
  - and earning replays
- check that the systray is working normally
- check that earnings animations x wallet balance are in sync
- no freezy

## Breaking Changes

\_\_

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

File: src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx [hunk 1]
```diff
@@ -41,11 +42,15 @@ const SeedPhrase = ({ setSection, words }: Props) => {
...
-    }
+    useEffect(() => {
+        const groups: string[][] = [];
+        for (let i = 0; i < words.length; i += 6) {
+            groups.push(words.slice(i, i + 6));
+        }
+        if (groups.length) {
+            setWordGroups(groups);
+        }
+    }, [words]);
```
Comment (MCozhusheck) [inline src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx:53]: is this useEffect necessary ? `words` comes from props so changes in `words` will change wordGroups anyway

File: src/App/AppWrapper.tsx [hunk 2]
```diff
@@ -54,15 +33,5 @@ export default function AppWrapper() {
         // eslint-disable-next-line react-hooks/exhaustive-deps
     }, []);
```
Comment (Misieq01) [inline src/App/AppWrapper.tsx:34]: We won't be bringing it back ?

Comment (shanimal08) [reply src/App/AppWrapper.tsx:34]: yea but it always exists in github :D just a pet peeve of mine to leave in big chunks of commented code, but i don't mind adding it back if you want? :D

File: src/containers/phase/Setup/components/AppVersion.tsx [hunk 3]
```diff
@@ -6,13 +6,20 @@ export default function AppVersion() {
     const [tariVersion, setTariVersion] = useState<string | null>(null);
 
     useEffect(() => {
+        let fetched = false;
```
Comment (MCozhusheck) [inline src/containers/phase/Setup/components/AppVersion.tsx:9]: is this variable necessary ? It's local variable if we want to verify we fetch only once we should use `useState` or `useRef` variable.

File: src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx [hunk 4]
```diff
@@ -41,11 +42,15 @@ const SeedPhrase = ({ setSection, words }: Props) => {
         setChecked(!checked);
     };
 
-    const wordGroups: string[][] = [];
-
-    for (let i = 0; i < words.length; i += 6) {
-        wordGroups.push(words.slice(i, i + 6));
-    }
+    useEffect(() => {
```
Comment (Misieq01) [inline src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx:45]: I don't think we need useEffect and useState here as words come with props so it will be rerendered either way

Comment (shanimal08) [reply src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx:45]: oh i updated `eslint-plugin-react-hooks` and it threw an error because of that loop out in the open ☹️ 

i can revert and revert the update?

**Review by MCozhusheck — CHANGES_REQUESTED** [review]

File: src/App/AppWrapper.tsx (hunk 2 above)
Comment (Misieq01) [reply src/App/AppWrapper.tsx:34]: I think its easier to uncomment code then look back through commit history but won't fight on it haha :D

File: src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx (hunk 1 above)
Comment (shanimal08) [reply src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx:53]: only changed it after the package bump https://github.com/tari-project/universe/pull/1229#discussion_r1908542970

 but yeah i wouldn't do that normally 😬 lmk if i should revert the update and these changes or just leave as is?

File: src/containers/phase/Setup/components/AppVersion.tsx [hunk 5]
```diff
@@ -6,13 +6,20 @@ export default function AppVersion() {
     const [tariVersion, setTariVersion] = useState<string | null>(null);
 
     useEffect(() => {
```
Comment (Misieq01) [inline src/containers/phase/Setup/components/AppVersion.tsx:8]: I don't think `let fetched` make a difference here its defined in scope of useEffect so it won't be preserved between executions of this useEffect

File: src-tauri/src/main.rs [hunk 6]
```diff
@@ -538,6 +536,23 @@ async fn setup_inner(
...
+                break;
+            }
+
+            interval.tick().await;
+            if let Ok(wallet) = commands::emit_tari_wallet_details(app_state).await {
+                drop(w_move_handle.emit("wallet_details", wallet));
+            }
+        }
+    });
+
```
[the remark this answers is not in the document]
Comment (shanimal08) [reply src-tauri/src/main.rs:555]: neat, thanks! should i do the same for the `miner_metrics` emit loop just above?:D

File: src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx (hunk 4 above)
Comment (Misieq01) [reply src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx:45]: What about removing hooks and just moving this loop to function outside component like `const groupSeedWords = (words: string[]) => {}` and then even you can do `groupSeedWords(words).map((group, groupIndex) => ...`

File: src/hooks/mining/useMiningMetricsUpdater.ts [hunk 7]
```diff
@@ -1,58 +1,40 @@
...
+
     const displayBlockHeight = useBlockchainVisualisationStore((s) => s.displayBlockHeight);
     const setDisplayBlockHeight = useBlockchainVisualisationStore((s) => s.setDisplayBlockHeight);
 
+    const deferredblock = useDeferredValue(currentBlockHeight);
+
     return useCallback(
         async (metrics: MinerMetrics) => {
             if (metrics) {
                 const isMining = metrics.cpu?.mining.is_mining || metrics.gpu?.mining.is_mining;
```
Comment (Misieq01) [inline src/hooks/mining/useMiningMetricsUpdater.ts:18]: These checks for node_connection and setting animation are no longer needed or they were moved somewhere else ?

Comment (shanimal08) [reply src/hooks/mining/useMiningMetricsUpdater.ts:18]: not needed since `useUiMiningStateMachine` checks against is_mining (gpu & cpu), so that actually caused a bit of weirdness with the animation states and i think `is_mining` for either is connected to being connected already on the BE? (could be wrong about that though)

Comment (Misieq01) [reply src/hooks/mining/useMiningMetricsUpdater.ts:18]: I was assuming that if someone added it then you can have `is_mining = true` and then `metrics.base_node?.is_connected either true or false` and when user wasn't connected to node then we didn't wanted to show animation of mining. I'm not sure but that's why I asked

File: src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx (hunk 4 above)
Comment (shanimal08) [reply src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx]: nice that did the trick :D updated :D

File: src-tauri/src/main.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (MCozhusheck) [reply src-tauri/src/main.rs]: > neat, thanks! should i do the same for the `miner_metrics` emit loop just above?:D

yes previous could be written similar

**Review by MCozhusheck — APPROVED** [review]

File: src/hooks/mining/useMiningMetricsUpdater.ts (hunk 7 above)
Comment (Misieq01) [reply src/hooks/mining/useMiningMetricsUpdater.ts:18]: Yeah I was thinking the same but someone added code that works like if there could be case where `base_node.connected` can be `false` and `is_mining` `true` so that's why I asked if you know for sure that this is not a case hah

Comment (shanimal08) [reply src/hooks/mining/useMiningMetricsUpdater.ts:18]: rats! oki awesome fixing, thanks so much!

File: src-tauri/Cargo.lock [hunk 8]
```diff
@@ -7612,16 +7606,18 @@ dependencies = [
...
 dependencies = [
  "tauri",
  "tauri-plugin",
 ]
 
 [[package]]
 name = "tauri-plugin-sentry"
-version = "0.3.0"
-source = "git+https://github.com/tari-project/sentry-tauri?rev=7554b9a8738d6442d175aa2add55ecc11c52842d#7554b9a8738d6442d175aa2add55ecc11c52842d"
+version = "0.2.0"
```
[the remark this answers is not in the document]
Comment (shanimal08) [reply src-tauri/Cargo.lock]: nice catch :D i just reverted to what it was before the tauri x tari fork but this branch is so old that a bunch of things have newer releases 😅 updated, ty!
